# Generated by Django 5.2.17 on 2026-08-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scheduled_for',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_covers', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_editor_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='publication_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=16),
        ),
    ]
