# Generated by Django 5.2.17 on 2026-08-21 15:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to_email", models.EmailField(max_length=254)),
                ("template_code", models.CharField(max_length=100)),
                ("context", models.JSONField(default=dict)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("related_object_ref", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template_code", "related_object_ref", "to_email"),
                        name="unique_email_message_idempotency",
                    )
                ],
            },
        ),
    ]
