# ruff: noqa: E501, I001
# Generated by Django 5.2.17 on 2026-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accountmembership_options_and_more"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["publication_state", "-published_at"], name="portfolios__publica_88be97_idx"
            ),
        ),
    ]
