# Generated by Django 5.2.17 on 2026-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_portfolio_portfolios__publica_88be97_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
