# ruff: noqa: E501, I001
# Generated by Django 5.2.17 on 2026-08-21 14:06

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountmembership",
            options={"base_manager_name": "all_objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="accountmembership",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
