# ruff: noqa: E501, I001
# Generated by Django 5.2.17 on 2026-08-21 14:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
        ("test_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="scopedrecord",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="scopedrecord",
            new_name="test_models_portfol_453b98_idx",
            old_name="test_models_sc_portfol_4e2a44_idx",
        ),
        migrations.AlterField(
            model_name="scopedrecord",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="portfolios.portfolio",
            ),
        ),
    ]
